### ISSUE TITLE
Could you please upload the code to classify buggy method to different types of template?

### ISSUE THREAD

**Issue by upcwanghaibo** [mxx1219/TRANSFER#1]
Hi,
I am very interested about the buggy code classification part, but the methods in the dataset are classified already and i can't find the code to classify a buggy code into different bug types.
So could you please upload this part of code?

Many Thanks.

**Comment by mxx1219** [comment]
We've been working on this part of code and documentation recently, and will release it as soon as possible. Thank you for your attention to our work.

**Comment by upcwanghaibo** [comment]
Very thanks for your reply, wish to see your update.

**Comment by upcwanghaibo** [comment]
> We've been working on this part of code and documentation recently, and will release it as soon as possible. Thank you for your attention to our work.

Hi, could you possibly upload those related code?

**Comment by mxx1219** [comment]
This part of the code is now open source in https://github.com/mxx1219/SC4FT.

> > We've been working on this part of code and documentation recently, and will release it as soon as possible. Thank you for your attention to our work.
> 
> Hi, could you possibly upload those related code?
