### ISSUE TITLE
Code for the Mutation-based part

### ISSUE THREAD

**Issue by Iroski** [mxx1219/TRANSFER#4]
Hello, me again :)

In the paper, you said that the mutation-score contains four types of information, which is the same of TraPT. I wonder if there is any open-source code/script that can generate the mutation score with PIT because I haven't found anything that can do this. If not, would you like to share this part to us? It looks such a lot of work to build it from scratch.🥺

Thank you!

**Comment by mxx1219** [comment]
> Hello, me again :)
> 
> In the paper, you said that the mutation-score contains four types of information, which is the same of TraPT. I wonder if there is any open-source code/script that can generate the mutation score with PIT because I haven't found anything that can do this. If not, would you like to share this part to us? It looks such a lot of work to build it from scratch.🥺
> 
> Thank you!

PIT itself is an open source tool (https://pitest.org/). If you want to know how to run it, you only need to read its official documentation. We recommend using the CMD command to run PIT by passing in required parameters (https://pitest.org/quickstart/commandline/). 

Our obtaining of the four granularity of change information is inspired by the two works of TraPT and DeepFL. These two papers (especially the former) have a detailed introduction on how to modify the source code of PIT tool to obtain the four granularity of change information. Specifically, for each buggy project (e.g., Chart_1 ), you need to use the PIT tool to execute the revelant test cases to obtain the initial four information (i.e., pass/fail, exception type, exception message, and the whole error text including stack traces.) Then using the mutation operators defined in the PIT tool to mutate the original program and to obtain the corresponding four kinds of information after the mutation. Finally comparing whether the information has changed in these four different granularities, and selecting a computing algorithm (such as ochiai-mutation) to calculate the final 4 suspicious scores.

We are also the first time to use PIT and mutation-based fault localization techniques, but found that it is not difficult to rewrite PIT source code and the subsequent scripts. It only takes about 7 to 10 days for one developer to complete this task. Running PIT takes a very long time and retains a lot of intermediate results (which is also a disadvantage of mutation-based fault localization method), so we deleted these intermediate experimental results after the experiment was completed, and only retained the final results that you can see in our github repository, that is, the mutation-based suspicious scores. Thus, we recommend that you try to reproduce this process yourself based on the details in TraPT, sorry about that.

**Comment by Iroski** [comment]
I got it. Thank you again!
