### ISSUE TITLE
Generating faulty_statement_set.pkl based on defects4j

### ISSUE THREAD

**Issue by nayeawon** [mxx1219/TRANSFER#6]
Hello :)
I'm Yeawon Na from Handong Global University in South Korea.
Thanks for your amazing work!
I'm currently exploring your work and I just wondered if I can have the code you used for generating the faulty_statement_set.pkl file based on the compiled defects4j cases.
I was curious about how faulty_statement_set.pkl was implemented and I want to try testing it on the other cases of defects4j.
Thanks again
Have a good day

**Comment by mxx1219** [comment]
> Hello :) I'm Yeawon Na from Handong Global University in South Korea. Thanks for your amazing work! I'm currently exploring your work and I just wondered if I can have the code you used for generating the faulty_statement_set.pkl file based on the compiled defects4j cases. I was curious about how faulty_statement_set.pkl was implemented and I want to try testing it on the other cases of defects4j. Thanks again Have a good day

Thanks for your interest in our work! 
You may pay attention to the research work "Evaluating and improving fault localization (ICSE'17)", one of the author of which is also the author of Defects4J dataset. It provides not only the method but also the implemented code/scripts for performing the statement-level fault annotation tasks on Defects4J dataset.

**Comment by nayeawon** [comment]
Thank you! I really appreciate it.
