### ISSUE TITLE
How to make several .pkl files manually?

### ISSUE THREAD

**Issue by nayeawon** [mxx1219/TRANSFER#7]
Hello
Thanks again for your amazing work😀

I'm currently following the steps for "Reproduce All Experiments from Scratch" introduced in README with using different target project (not Defects4j).
And I got stuck at running data_preprocess_for_d4j.py. 

As I'm trying to literally reproduce all experiments, there are some data already generated without a source code for making it.

1. Regarding `spectrum.pkl`, I ran GZoltar but got different format of results. I wonder if you run the code/script from the "Evaluating and improving fault localization (ICSE'17)." If not, could you please share the source code for generating `spectrum.pkl`?

2. Regarding `src_code.pkl` and `checker_info.pkl`, would it be possible to get the source code for generating the files? I tried to run https://github.com/mxx1219/SC4FT but not sure if it's right.

Thanks!

**Comment by mxx1219** [comment]
> 

Thanks for your continued interest in our work.

The replies to your two questions are as follows:

1) Let's take Chart_1 in the Defects4J benchmark as an example to explain how to generate "spectrum.pkl" from the original suspicious file generated by GZoltar. 
    a) We use the running script provided by ICSE'17 to run GZoltar, and specify the fault localization algorithm as Ochiai. The format of the generated suspicious file should be consistent with yours, as shown in the attached file.
    b) We only keep the statement (line in the suspicious file) whose suspicious score is greater than 0. For Chart_1, there are 629 lines should be kept. We save the position of each statement (format: package.class_name@line_number) to generate "statement.pkl", and save the suspicious score of each statement under the Ochiai algorithm.
    c) Obtaining the suspicious file under Tarantula and DStar algorithms by GZoltar. And for each statement in "statement.pkl", the corresponidng suspicious scores of Tarantula and DStar for this statement are searched and saved (if not found, the default score 0.0 is used). Finally, the file "spectrum.pkl" is constructed by concatenating the three suspicious scores of each statement in "statement.pkl". For example, the first statement of Chart_1 is "org.jfree.chart.renderer.category.AbstractCategoryItemRenderer@1793", and the three suspicious scores ​​corresponding to it is [1.0, 1.0, 0.0]. The same goes for other statements and other bug versions.

Gzoltar_localization_result (Chart_1): 
[ochiai.ranking.csv](https://github.com/mxx1219/TRANSFER/files/10465093/ochiai.ranking.csv)


2) SCF4T is used to judge whether the code changes between the before_fix_method and the after_fix_method conform to the predefined code change actions of the fix templates used in the paper (during the construction of the large-scale datasets). However, the file "checker_info.pkl" contains the mask information for the target project (e.g. Chart_1 in Defects4J), that is, whether the currently focused statement contains the corresponding necessary syntax ingredients of different bug types, which are shown in Table 1 in the paper. For example, the mask information of the first suspicious statement (of Chart_1) "org.jfree.chart.renderer.category.AbstractCategoryItemRenderer@1793" is "[1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1]", indicating that the 5 templates with the mask value 1 have the necessary ingredients, while the others (value 0) do not have. 

![062e968fda89448b1c8cbcef90bf6f8](https://user-images.githubusercontent.com/17797550/213678742-86c6973f-dbe8-454d-a9bc-06f14055d193.png)

We only considered running experiments on the D4J dataset at that time, so for other researchers to more easily replicate our experiments, we only put out the collated intermediate data. The code/scripts of this part may take some time to sort out and release if you need it (3-4 weeks). And if in a hurry, you could also attempt to use JDK library to develop a syntax filter with the standard provided in the Table 1.

**Comment by nayeawon** [comment]
I deeply appreciate for your detailed explanation.
Could you please share your script for generating "checker_info.pkl" when it is available?
By then, I will also be working on the syntax filter too.
Thanks again.

**Comment by mxx1219** [comment]
> I deeply appreciate for your detailed explanation. Could you please share your script for generating "checker_info.pkl" when it is available? By then, I will also be working on the syntax filter too. Thanks again.

Ok, no problem.

**Comment by nayeawon** [comment]
Hi @mxx1219 
Would there be any updates so far?

**Comment by mxx1219** [comment]
> Hi @mxx1219 Would there be any updates so far?

Yes, please refer to https://github.com/mxx1219/NIChecker.

**Comment by nayeawon** [comment]
> Yes, please refer to https://github.com/mxx1219/NIChecker.

I deeply appreciate it!
Thank you

**Comment by mxx1219** [comment]
> > Yes, please refer to https://github.com/mxx1219/NIChecker.
> 
> I deeply appreciate it! Thank you

You are welcome :)
